location = "{{ location }}"

[api]
user = "user"
password = "password"

[ipa]
host = "ipa_host"
user = "user"
password = "password"

[[site]]
location = "l1"
name = "s1"

[[site]]
location = "l2"
name = "s2"



[redis]
    [redis.hf]
    host = "10.2.3.4"
    username = "user"
    password = "password"

    [redis.sh]
    host = "10.2.3.5"
    username = "user"
    password = "password"
