location = "{{ location }}"

[api]
user = "user"
password = "password"

[[redis]]
host = "10.2.3.4"
username = "user"
password = "password"

[[redis]]
host = "10.2.3.5"
username = "user"
password = "password"
