location = "{{ location }}"

[api]
user = "user"
password = "password"

[redis]
    [redis.hf]
    host = "10.2.3.4"
    username = "user"
    password = "password"

    [redis.sh]
    host = "10.2.3.5"
    username = "user"
    password = "password"
